name: 'Build And Publish Images'
description: 'Builds and publishes images with pack'
inputs:
  version:
    description: 'dataflow version'
    required: true
  dockerhub-username:
    description: 'dockerhub username'
    required: true
  dockerhub-password:
    description: 'dockerhub password'
    required: true
  GCR_JSON_KEY:
    description: 'GCR_JSON_KEY'
    required: true
runs:
  using: "composite"
  steps:
  - name: Install pack
    uses: jvalkeal/build-zoo-handler@v0.0.4
    with:
      pack-version: 0.30.0

    # docker hub login
  - name: Login to docker.io
    uses: docker/login-action@v1
    with:
      username: ${{ inputs.dockerhub-username }}
      password: ${{ inputs.dockerhub-password }}
  - name: Login to GCR
    uses: docker/login-action@v3
    with:
      registry: gcr.io
      username: _json_key
      password: ${{ inputs.GCR_JSON_KEY }}
  - name: Build Images
    env:
      TAG: ${{ inputs.version }}
    shell: bash
    run: ${{ github.action_path }}/build-images.sh

  # build/publish support images
  - name: Publish Grafana Prometheus
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/prometheus/docker/grafana
      push: true
      tags: springcloud/spring-cloud-dataflow-grafana-prometheus:${{ inputs.version }}
  - name: Publish Grafana InfluxDB
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/influxdb/docker/grafana
      push: true
      tags: springcloud/spring-cloud-dataflow-grafana-influxdb:${{ inputs.version }}
  - name: Publish Prometheus Local
    uses: docker/build-push-action@v2
    with:
      context: src/grafana/prometheus/docker/prometheus-local
      push: true
      tags: springcloud/spring-cloud-dataflow-prometheus-local:${{ inputs.version }}
