apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_configs:
      - job_name: 'scdf'
        metrics_path: '/actuator/prometheus'
        file_sd_configs:
          - files:
              - /etc/prometheus/targets.json
            refresh_interval: 30s
    
      - job_name: 'local-rsocket-proxy'
        scrape_interval: 10s
        scrape_timeout: 9s
        metrics_path: '/metrics/proxy'
        static_configs:
          - targets: ['prometheus-rsocket-proxy:8080']
    
      - job_name: 'local-rsocket-connected'
        scrape_interval: 10s
        scrape_timeout: 9s
        metrics_path: '/metrics/connected'
        static_configs:
          - targets: ['prometheus-rsocket-proxy:8080']
