apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql57
  labels:
    app: mysql57
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi