apiVersion: v1
kind: Service
metadata:
  name: mysql57
  labels:
    app: mysql57
spec:
  type: NodePort
  ports:
    - name: mysql57
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql57
