scdf:
  binder:
    type: rabbit
  server:
    service:
      type: LoadBalancer
    env:
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
        value: "true"
  skipper:
  registry:
    secret:
      ref: "reg-creds-dockerhub"
