name: Publish Bundle
description: Publish Bundle
inputs:
  path:
    description: path to bundle files
    required: true
  repository:
    description: repository to publish
    required: true
  project-directory:
    description: The working directory
    required: true
  version:
    description: semver version
    required: true
  SRP_CLIENT_ID:
    description: secrets.SRP_CLIENT_ID
    required: false
  SRP_CLIENT_SECRET:
    description: secrets.SRP_CLIENT_SECRET
    required: false
runs:
  using: "composite"
  steps:
  - name: Setup Envs
    shell: bash
    run: |
      echo RTAG=R$(date +%y%m%d%s%N) >> $GITHUB_ENV
  - name: Tanzu Dance
    id: tanzu-dance
    env:
      BUNDLE_PATH: ${{ inputs.path }}
      REPOSITORY: ${{ inputs.repository }}
      VERSION: ${{ inputs.version }}
      SRP_CLIENT_ID: ${{ inputs.SRP_CLIENT_ID }}
      SRP_CLIENT_SECRET: ${{ inputs.SRP_CLIENT_SECRET }}
    shell: bash
    working-directory: ${{ inputs.project-directory }}
    run: |
      if [ "$USE_SRP" == "true" ]; then
        if [ "$SRP_SCRIPTS" == "" ]; then
          echo "SRP_SCRIPTS not defined"
          exit 2
        fi
        if [[ "$REPOSITORY" == *"-package"* ]]; then
          export OBSERVATION=package-publish
        else
          export OBSERVATION=repository-publish
        fi
        export OUTPUT_VERSION=$VERSION
        $SRP_SCRIPTS/run-under-observer.sh "${{ github.action_path }}/publish-bundle.sh"
      else
        "${{ github.action_path }}/publish-bundle.sh"
      fi
