apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
        - name: scdf-server
          image: dev.registry.pivotal.io/p-scdf-for-kubernetes/scdf-pro-server:${DATAFLOW_PRO_VERSION}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /workspace/config
              readOnly: true
            - name: database
              mountPath: /etc/secrets/database
              readOnly: true
          ports:
            - hostPort: 9393
              containerPort: 9393
          livenessProbe:
            httpGet:
              path: /management/health
              port: 9393
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /management/info
              port: 9393
            initialDelaySeconds: 45
          startupProbe:
            httpGet:
              port: 9393
              path: /management/health
            failureThreshold: 3
            timeoutSeconds: 3
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            limits:
              cpu: 1.0
              memory: 2048Mi
            requests:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: LANG
              value: en_US.utf8
            - name: LC_ALL
              value: en_US.utf8
            - name: JDK_JAVA_OPTIONS
              value: '-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: SPRING_PROFILES_ACTIVE
              value: 'kubernetes'
            - name: SERVER_PORT
              value: '9393'
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'false'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI
              value: 'docker://springcloud/spring-cloud-dataflow-composed-task-runner:${DATAFLOW_VERSION}'
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
              value: 'false'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: 'false'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
              value: /etc/secrets
            - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
              value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
              # Provide the Skipper service location
            - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
              value: 'http://${SKIPPER_SERVICE_HOST}:${SKIPPER_SERVICE_PORT}/api'
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: scdf-datasource
            - name: SPRING_JPA_DATABASE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: SPRING_JPA_DATABASE_PLATFORM
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_TEST_ON_BORROW
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_TEST_ON_BORROW
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_VALIDATION_QUERY
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_VALIDATION_QUERY
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USE_UNICODE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USE_UNICODE
                  name: scdf-datasource
            - name: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CHARACTER_ENCODING
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CHARACTER_ENCODING
                  name: scdf-datasource
      serviceAccountName: scdf-sa
      volumes:
        - name: config
          configMap:
            name: scdf-server
            items:
              - key: 'application-kubernetes.yaml'
                path: 'application-kubernetes.yaml'
        - name: database
          secret:
            secretName: ${DATABASE}
