scdf:
  server:
    # for minikube
    # service:
    #   type: NodePort
    # for public cloud
    # service:
    #   type: LoadBalancer
    config:
      spring:
        cloud:
          dataflow:
            container:
              registry-configurations:
                ghcr:
                  registry-host: ghcr.io
                  authorization-type: dockeroauth2
                  # replace to your gh username
                  user: <username>
                  # replace to your gh pat having read:packages scope
                  secret: <pat>

