apiVersion: v1
kind: Service
metadata:
  name: prometheus-rsocket-proxy
  labels:
    app: prometheus-rsocket-proxy
spec:
  selector:
    app: prometheus-rsocket-proxy
  ports:
    - name: scrape
      port: 8080
      targetPort: 8080
    - name: rsocket
      port: 7001
      targetPort: 7001
  type: LoadBalancer
