name: Carvel Worker

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      # zoo extract and ensure
      - name: Extract Zoo Context Properties
        uses: jvalkeal/build-zoo-handler@v0.0.4
        with:
          dispatch-handler-extract-context-properties: true
          ensure-env: BUILD_ZOO_HANDLER_spring_cloud_dataflow_version
    outputs:
      dataflow-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      skipper-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      server-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
      ctr-version: ${{ env.BUILD_ZOO_HANDLER_spring_cloud_dataflow_version }}
  publish:
    name: Publish
    needs:
      - prepare
    uses: ./.github/workflows/common-carvel.yml
    with:
      package-name: 'scdf'
      package-version: ${{ needs.prepare.outputs.server-version }}
      package-bundle: 'springcloud/scdf-oss-package'
      repository-bundle: 'springcloud/scdf-oss-repo'
      dataflow-version: ${{ needs.prepare.outputs.dataflow-version }}
      server-version: ${{ needs.prepare.outputs.server-version }}
      ctr-version: ${{ needs.prepare.outputs.dataflow-version }}
      skipper-version: ${{ needs.prepare.outputs.skipper-version }}
      server-repository: 'springcloud/spring-cloud-dataflow-server'
      skipper-repository: 'springcloud/spring-cloud-skipper-server'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  finalize:
    name: Finalize
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      # zoo success
      - name: Notify Build Success Zoo Handler Controller
        uses: jvalkeal/build-zoo-handler@v0.0.4
        with:
          dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
          dispatch-handler-client-payload-data: >
            {
              "event": "carvel-succeed"
            }

      # zoo failure
      - name: Notify Build Failure Zoo Handler Controller
        if: ${{ failure() }}
        uses: jvalkeal/build-zoo-handler@v0.0.4
        with:
          dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
          dispatch-handler-client-payload-data: >
            {
              "event": "carvel-failed"
            }
