name: CI IT Security

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    name: Security IT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'liberica'
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.8
        maven-mirror: 'https://dlcdn.apache.org/maven/maven-3/'
    - name: Run Security IT
      run: |
        mvn \
          -s .settings.xml \
          -pl spring-cloud-dataflow-server \
          -Dgroups=oauth \
          -Pfailsafe \
          --batch-mode \
          integration-test
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: ${{ success() || failure() }}
      with:
        name: Integration Tests
        path: '**/failsafe-reports/*IT.xml'
        reporter: java-junit
        list-tests: failed
    - name: 'Action: Upload Unit Test Results'
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.group }}-test-results-surefire
        path: './**/target/surefire-reports/**/*.*'
        retention-days: 7
        if-no-files-found: ignore
    - name: 'Action: Upload Integration Test Results'
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.group }}-test-results-failsafe
        path: './**/target/failsafe-reports/**/*.*'
        retention-days: 7
        if-no-files-found: ignore
